[package]
edition = "2021"
name = "alphametics"
version = "1.3.0"

[dependencies]
criterion = { version = "0.4.0", features = [ "html_reports" ]}
itertools = "0.10.5"

[[bench]]
name = "alphametics"
harness = false
